language: python
python:
  - '3.6'
env:
  - SECRET_KEY=FILL_UP_flask_secret_key
services:
  - postgresql
before_script:
  - psql -c 'create database {{cookiecutter.project_slug}}_test;' -U postgres
install:
  - pip install -r requirements/local.txt
  - npm install
  - npm run build_dev
script:
  - pytest
after_success:
  - codecov -t FILL_UP_codecov_token
deploy:
  provider: heroku
  app: flaskme
  api_key:
    secure: FILL_UP_heroku_encrypted_auth_token
